// Fonts whose Latin preview is meaningless: placeholder/wireframe fonts, barcodes, icon fonts, and
// dingbats. CJK fonts are not listed; they render their family name in Latin just fine.
export const FAMILIES_TO_SKIP_PREVIEW_IMAGE = new Set<string>([
  'Flow Block',
  'Flow Circular',
  'Flow Rounded',
  'Libre Barcode 128',
  'Libre Barcode 128 Text',
  'Libre Barcode 39',
  'Libre Barcode 39 Extended',
  'Libre Barcode 39 Extended Text',
  'Libre Barcode 39 Text',
  'Libre Barcode EAN13 Text',
  'Linefont',
  'Material Icons',
  'Material Icons Outlined',
  'Material Icons Round',
  'Material Icons Sharp',
  'Material Icons Two Tone',
  'Material Symbols',
  'Material Symbols Outlined',
  'Material Symbols Rounded',
  'Material Symbols Sharp',
  'Palette Mosaic',
  'Redacted',
  'Redacted Script',
  'Wavefont',
  'Yarndings 12',
  'Yarndings 12 Charted',
  'Yarndings 20',
  'Yarndings 20 Charted',
]);
