// Copied from the paper repo

export const FAMILIES_TO_SKIP_PREVIEW_IMAGE = new Set<string>([
  'Aoboshi One',
  'Asta Sans',
  'Bagel Fat One',
  'BIZ UDGothic',
  'BIZ UDMincho',
  'BIZ UDPMincho',
  'BIZ UDPGothic',
  'Black And White Picture',
  'Black Han Sans',
  'Blaka Ink',
  'Bungee Spice',
  'Bungee Tint',
  'Cactus Classical Serif',
  'Cherry Bomb One',
  'Chiron Hei HK',
  'Chiron Sung HK',
  'Chocolate Classical Sans',
  'Chokokutai',
  'Cute Font',
  'Darumadrop One',
  'Dela Gothic One',
  'Diphylleia',
  'Do Hyeon',
  'Dokdo',
  'Dongle',
  'DotGothic16',
  'East Sea Dokdo',
  'Flow Block',
  'Flow Circular',
  'Flow Rounded',
  'Gaegu',
  'Gamja Flower',
  'Gasoek One',
  'Gothic A1',
  'Gowun Batang',
  'Gowun Dodum',
  'Grandiflora One',
  'Gugi',
  'Hachi Maru Pop',
  'Hahmlet',
  'Hi Melody',
  'Hina Mincho',
  'Honk',
  'Huninn',
  'Iansui',
  'IBM Plex Sans JP',
  'IBM Plex Sans KR',
  'Jua',
  'Kaisei Decol',
  'Kaisei HarunoUmi',
  'Kaisei Opti',
  'Kaisei Tokumin',
  'Kalnia Glaze',
  'Kapakana',
  'Kirang Haerang',
  'Kiwi Maru',
  'Klee One',
  'Kosugi',
  'Kosugi Maru',
  'Libre Barcode 128',
  'Libre Barcode 128 Text',
  'Libre Barcode 39',
  'Libre Barcode 39 Extended',
  'Libre Barcode 39 Extended Text',
  'Libre Barcode 39 Text',
  'Libre Barcode EAN13 Text',
  'Linefont',
  'Liu Jian Mao Cao',
  'Long Cang',
  'LXGW Marker Gothic',
  'LXGW WenKai Mono TC',
  'LXGW WenKai TC',
  'M PLUS 1',
  'M PLUS 1 Code',
  'M PLUS 1p',
  'M PLUS 2',
  'M PLUS Rounded 1c',
  'Ma Shan Zheng',
  'Material Icons',
  'Material Icons Outlined',
  'Material Icons Round',
  'Material Icons Sharp',
  'Material Icons Two Tone',
  'Material Symbols',
  'Material Symbols Outlined',
  'Material Symbols Rounded',
  'Material Symbols Sharp',
  'Mochiy Pop One',
  'Mochiy Pop P One',
  'Moirai One',
  'Monomaniac One',
  'Murecho',
  'Nabla',
  'Nanum Brush Script',
  'Nanum Gothic',
  'Nanum Gothic Coding',
  'Nanum Myeongjo',
  'Nanum Pen Script',
  'New Tegomin',
  'Noto Sans HK',
  'Noto Sans JP',
  'Noto Sans KR',
  'Noto Sans SC',
  'Noto Sans TC',
  'Noto Serif HK',
  'Noto Serif JP',
  'Noto Serif KR',
  'Noto Serif SC',
  'Noto Serif TC',
  'Orbit',
  'Palette Mosaic',
  'Poor Story',
  'Potta One',
  'Rampart One',
  'Redacted',
  'Redacted Script',
  'Reggae One',
  'Rock 3D',
  'RocknRoll One',
  'Sawarabi Gothic',
  'Sawarabi Mincho',
  'Shippori Antique',
  'Shippori Antique B1',
  'Shippori Mincho',
  'Shippori Mincho B1',
  'Shizuru',
  'Slackside One',
  'Song Myung',
  'Stick',
  'Stylish',
  'Train One',
  'Tsukimi Rounded',
  'UoqMunThenKhung',
  'Wavefont',
  'WDXL Lubrifont JP N',
  'WDXL Lubrifont SC',
  'WDXL Lubrifont TC',
  'Yarndings 12',
  'Yarndings 12 Charted',
  'Yarndings 20',
  'Yarndings 20 Charted',
  'Yeon Sung',
  'Yomogi',
  'Yuji Boku',
  'Yuji Hentaigana Akari',
  'Yuji Hentaigana Akebono',
  'Yuji Hentigana Akari',
  'Yuji Hentigana Akebono',
  'Yuji Mai',
  'Yuji Syuku',
  'Yusei Magic',
  'ZCOOL KuaiLe',
  'ZCOOL QingKe HuangYou',
  'ZCOOL XiaoWei',
  'Zen Antique',
  'Zen Antique Soft',
  'Zen Kaku Gothic Antique',
  'Zen Kaku Gothic New',
  'Zen Kurenaido',
  'Zen Maru Gothic',
  'Zen Old Mincho',
  'Zhi Mang Xing',
]);