// Copied from the paper repo

// Names for registered OpenType features
// https://learn.microsoft.com/en-us/typography/opentype/spec/featurelist
// Some features "should not generally be exposed to the user" as suggested by the OpenType spec,
// and are not present in this list.
export const FONT_FEATURE_NAMES = {
  afrc: 'Alternative fractions',
  apkn: 'Kerning for alternate proportional widths',
  calt: 'Contextual alternates',
  case: 'Case-sensitive forms',
  chws: 'Contextual half-width spacing',
  clig: 'Contextual ligatures',
  cpct: 'Centered CJK punctuation',
  cpsp: 'Capital spacing',
  cswh: 'Contextual swash',
  // cv01 to cv99
  ...Object.assign(
    {},
    ...new Array(99)
      .fill(0)
      .map((_, i) => ({ [`cv${(i + 1).toString().padStart(2, '0')}`]: `Character variant ${i + 1}` }))
  ),
  c2pc: 'Petite capitals from capitals',
  c2sc: 'Small capitals from capitals',
  dlig: 'Discretionary ligatures',
  dnom: 'Denominators',
  expt: 'Expert forms',
  falt: 'Final glyph on line alternates',
  frac: 'Fractions',
  fwid: 'Full widths',
  halt: 'Alternate half widths',
  hist: 'Historical forms',
  hkna: 'Horizontal kana alternates',
  hlig: 'Historical ligatures',
  hngl: 'Hangul',
  hojo: 'Hojo kanji forms',
  hwid: 'Half widths',
  ital: 'Italics',
  jalt: 'Justification alternates',
  jp78: 'JIS78 forms',
  jp83: 'JIS83 forms',
  jp90: 'JIS90 forms',
  jp04: 'JIS2004 forms',
  kern: 'Kerning',
  lfbd: 'Left bounds',
  liga: 'Standard ligatures',
  lnum: 'Lining figures',
  mgrk: 'Mathematical greek',
  nalt: 'Alternate annotation forms',
  nlck: 'NLC kanji forms',
  numr: 'Numerators',
  onum: 'Oldstyle figures',
  opbd: 'Optical bounds',
  ordn: 'Ordinals',
  ornm: 'Ornaments',
  palt: 'Proportional alternate widths',
  pcap: 'Petite capitals',
  pkna: 'Proportional kana',
  pnum: 'Proportional figures',
  pwid: 'Proportional widths',
  qwid: 'Quarter widths',
  rand: 'Randomize',
  rtbd: 'Right bounds',
  ruby: 'Ruby notation forms',
  salt: 'Stylistic alternates',
  sinf: 'Scientific inferiors',
  size: 'Optical size',
  smcp: 'Small capitals',
  smpl: 'Simplified forms',
  // ss01 to ss20
  ...Object.assign(
    {},
    ...new Array(20).fill(0).map((_, i) => ({ [`ss${(i + 1).toString().padStart(2, '0')}`]: `Stylistic set ${i + 1}` }))
  ),
  subs: 'Subscript',
  sups: 'Superscript',
  swsh: 'Swash',
  titl: 'Titling',
  tnam: 'Traditional name forms',
  tnum: 'Tabular figures',
  trad: 'Traditional forms',
  twid: 'Third widths',
  unic: 'Unicase',
  valt: 'Alternate vertical metrics',
  vapk: 'Kerning for alternate proportional vertical metrics',
  vchw: 'Vertical contextual half-width spacing',
  vert: 'Vertical alternates',
  vhal: 'Alternate vertical half metrics',
  vkna: 'Vertical kana alternates',
  vkrn: 'Vertical kerning',
  vpal: 'Proportional alternate vertical metrics',
  vrt2: 'Vertical alternates and rotation',
  vrtr: 'Vertical alternates for rotation',
  zero: 'Slashed zero',
};
